[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_nft_anchor = "Bi6BaPexHVoZkk8skXJoAYFb7iG5tXdoBgeXfPE7R7gG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
